name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: vimalthanth70
        password: ${{ secrets.DOCKER_ADMIN_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vimalthanth70/thinkbridge:latest

    - name: Verify Pushed Image
      run: docker pull vimalthanth70/thinkbridge:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull vimalthanth70/thinkbridge:latest
          sudo docker stop thinkbridge || true
          sudo docker rmi thinkbridge || true
          sudo docker run -d --name thinkbridge -p 4173:4173 -e VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }} -p 3000:3000 vimalthanth70/thinkbridge:latest