name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Prepare Dockerfile
      run: cp ./docker/Dockerfile ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ADMIN_USERNAME }}
        password: ${{ secrets.DOCKER_ADMIN_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_ADMIN_USERNAME }}/thinkbridge:latest

    - name: Verify Pushed Image
      run: docker pull ${{ secrets.DOCKER_ADMIN_USERNAME }}/thinkbridge:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKER_ADMIN_USERNAME }}/thinkbridge:latest
          sudo docker stop thinkbridge || true
          sudo docker rmi thinkbridge || true
          sudo docker run -d --name thinkbridge -p 5173:5173 -e VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }} -p 3000:3000 ${{ secrets.DOCKER_ADMIN_USERNAME }}/thinkbridge:latest